### PR TITLE
Error page added

### PR DESCRIPTION
**Pull request by PatilHarshh**
Error page is added Please check #68

### CODE REVIEW

**Comment by PatilHarshh** [comment]
@AtriSukul1508 please check

**Comment by AtriSukul1508** [comment]
@PatilHarshh screenshot of the page please

**Comment by PatilHarshh** [comment]
Screenshot (130)
@AtriSukul1508

**Review by AtriSukul1508 — APPROVED** [review]

**Comment by PatilHarshh** [comment]
@AtriSukul1508 bro u forgot to assign in both PR + issue

**Comment by PatilHarshh** [comment]
@AtriSukul1508

**Comment by AtriSukul1508** [comment]
@PatilHarshh what do you mean by "forgot to assign in both PR + issue", the issue has already been assigned to you

**Pull request merged**
